Fix

diff --git a/.github/workflows/memleaks.yml b/.github/workflows/memleaks.yml
--- a/.github/workflows/memleaks.yml
+++ b/.github/workflows/memleaks.yml
@@ -1,4 +1,4 @@
-name: Memory leak check
+name: Memory leak checker
 on: [push]
 permissions:
   contents: read
@@ -20,7 +20,7 @@ jobs:
       - name: Configure Tcl
         working-directory: tcl/unix
         run: |
-          ./configure --enable-symbols=all --prefix $HOME/tcl_install || {
+          ./configure --enable-symbols=all --prefix=$HOME/tcl_install || {
             cat config.log
             echo "::error::Failure during Configure Tcl"
             exit 1
@@ -40,13 +40,42 @@ jobs:
             exit 1
           }
 
+      - name: Checkout tclvfs
+        uses: actions/checkout@v4
+        with:
+          repository: chpock/tclvfs
+          ref: main
+          path: tclvfs
+      - name: Configure tclvfs
+        working-directory: tclvfs
+        run: |
+          ./configure --enable-symbols=all --with-tcl=$HOME/tcl_install/lib --prefix=$HOME/tcl_install --exec-prefix=$HOME/tcl_install || {
+            cat config.log
+            echo "::error::Failure during Configure tclvfs"
+            exit 1
+          }
+      - name: Build tclvfs
+        working-directory: tclvfs
+        run: |
+          make -j || {
+            echo "::error::Failure during Build tclvfs"
+            exit 1
+          }
+      - name: Install tclvfs
+        working-directory: tclvfs
+        run: |
+          make install || {
+            echo "::error::Failure during Install tclvfs"
+            exit 1
+          }
+
       - name: Checkout
         uses: actions/checkout@v4
         with:
           submodules: recursive
       - name: Configure
         run: |
-          ./configure --with-tcl=$HOME/tcl_install --enable-symbols=all || {
+          ./configure --enable-symbols=all --with-tcl=$HOME/tcl_install/lib || {
             cat config.log
             echo "::error::Failure during Configure"
             exit 1
